name: build_and_release #名称随意
on:
  push: #设置触发规则
    branches:
      - main
      - master
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install and test
        run: |
          yarn install
          cd excalidraw-app
          yarn build
          tar -zcvf excalidraw-app.tar.gz ./build
          mv ./excalidraw-app.tar.gz ..
      - name: Release
        uses: softprops/action-gh-release@v2 #具体参考https://github.com/softprops/action-gh-release
        if: startsWith(github.ref, 'refs/tags/') # 设置为有tag才进行上传
        with:
          body: Auto Create Release
          files: |
            excalidraw-app.tar.gz
